CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "unique_id" varchar UNIQUE NOT NULL,
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "role" varchar,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "workspaces" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "unique_id" varchar UNIQUE NOT NULL,
  "name" varchar NOT NULL,
  "owner" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "workspace_members" (
  "workspace_id" varchar NOT NULL,
  "user_id" varchar NOT NULL,
  PRIMARY KEY ("workspace_id", "user_id")
);

CREATE TABLE "teams" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "unique_id" varchar UNIQUE NOT NULL,
  "workspace_id" varchar NOT NULL,
  "name" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "team_members" (
  "team_id" varchar NOT NULL,
  "user_id" varchar NOT NULL,
  PRIMARY KEY ("team_id", "user_id")
);

CREATE TABLE "boards" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "unique_id" varchar UNIQUE NOT NULL,
  "team_id" varchar NOT NULL,
  "title" varchar,
  "description" varchar,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

ALTER TABLE "teams" ADD FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("unique_id");

ALTER TABLE "workspaces" ADD FOREIGN KEY ("owner") REFERENCES "users" ("unique_id");

ALTER TABLE "workspace_members" ADD FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("unique_id");

ALTER TABLE "workspace_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("unique_id");

ALTER TABLE "team_members" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("unique_id");

ALTER TABLE "team_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("unique_id");

ALTER TABLE "boards" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("unique_id");
